export const feelings = {
    heureux: "#FFD580",
    stresse: "#FF9999",
    relaxe: "#A8D5BA",
    excite: "#FFCCB3",
    fatigue: "#D3D3D3",
    productif: "#A3C1E0",
    inquiet: "#E6A4B4",
    motive: "#FFD1DC",
    frustre: "#E6B0AA",
    gratitude: "#FFECB3",
    anxieux: "#B3CDE0",
    confiant: "#C2E3C7",
    energise: "#FFF1B5",
    decu: "#E0B3B3",
    epanoui: "#FFC9A7",
    indecis: "#E0DED8",
    solitaire: "#C5C8D1",
    amoureux: "#FFB6C1",
    curieux: "#C7DDE0",
    enColere: "#F4A6A6",
}
